services:
  backend:
    build:
      context: ./plant-pal-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    container_name: capstone_backend

  frontend:
    build:
      context: ./plant-pal-frontend
      args:
        REACT_APP_API_BASE_URL: "http://backend:5000"
    ports:
      - "3000:80"
    depends_on:
      - backend
    container_name: capstone_frontend